export enum StatusTypeOrder {
    WAITING = 'ESPERA',
    PENDING = 'PENDIENTE',
    ACCEPT = 'ACEPTADA',
    PROCESSING = 'EN PROCESO',
    READY = 'LISTOS',
    CONCLUDES = 'CONCLUIDA',
    REJECTED = 'RECHAZADA',
}
