export const categoriesData = [
  // Existentes (restaurantes)
  { cName: 'Restaurante de Mariscos', csDescription: 'Delicias del mar frescas y sabrosas', cPathImage: '/imagenes/restaurante_mariscos.jpg' },
  { cName: 'Restaurante de Carnes', csDescription: 'Cortes de carne premium y parrilladas', cPathImage: '/imagenes/restaurante_carnes.jpg' },
  { cName: 'Restaurante de Vegetariano/Vegano', csDescription: 'Platos saludables y creativos sin carne', cPathImage: '/imagenes/restaurante_vegetariano.jpg' },
  { cName: 'Cafetería', csDescription: 'Café de calidad y bocadillos deliciosos', cPathImage: '/imagenes/cafeteria.jpg' },
  { cName: 'Pastelería', csDescription: 'Pasteles, postres y dulces irresistibles', cPathImage: '/imagenes/pasteleria.jpg' },
  { cName: 'Bar de Tapas', csDescription: 'Tapas variadas y bebidas refrescantes', cPathImage: '/imagenes/bar_tapas.jpg' },
  { cName: 'Sushi', csDescription: 'Sushi fresco y rolls creativos', cPathImage: '/imagenes/restaurante_sushi.jpg' },
  { cName: 'Comida Fusion', csDescription: 'Innovadoras combinaciones de sabores de todo el mundo', cPathImage: '/imagenes/restaurante_fusion.jpg' },
  { cName: 'Restaurante Chino', csDescription: 'Comida china auténtica', cPathImage: '/imagenes/restaurante_chino.jpg' },
  { cName: 'Restaurante Mexicano', csDescription: 'Deliciosa comida mexicana', cPathImage: '/imagenes/restaurante_mexicano.jpg' },
  { cName: 'Restaurante Italiano', csDescription: 'Auténtica comida italiana', cPathImage: '/imagenes/restaurante_italiano.jpg' },
  { cName: 'Restaurante Japonés', csDescription: 'Sushi y comida japonesa', cPathImage: '/imagenes/restaurante_japones.jpg' },
  { cName: 'Restaurante Coreano', csDescription: 'Comida coreana tradicional', cPathImage: '/imagenes/restaurante_coreano.jpg' },
  { cName: 'Comida Rápida', csDescription: 'Sabrosas opciones de comida rápida', cPathImage: '/imagenes/comida_rapida.jpg' },
  { cName: 'Pizzería', csDescription: 'Auténtica pizza recién horneada', cPathImage: '/imagenes/pizzeria.jpg' },
  { cName: 'Restaurante Español', csDescription: 'Tapas y platos españoles', cPathImage: '/imagenes/restaurante_espanol.jpg' },

  // Nuevos (otros tipos de comercio)
  { cName: 'Agencia de viajes', csDescription: 'Planea tus vacaciones o viajes de negocios', cPathImage: '/imagenes/agencia_viajes.jpg' },
  { cName: 'Almacén de ropa', csDescription: 'Moda para todos los estilos y temporadas', cPathImage: '/imagenes/almacen_ropa.jpg' },
  { cName: 'Automotriz / Taller', csDescription: 'Servicio técnico para vehículos', cPathImage: '/imagenes/taller_automotriz.jpg' },
  { cName: 'Bar', csDescription: 'Bebidas, ambiente y buena música', cPathImage: '/imagenes/bar.jpg' },
  { cName: 'Barbería', csDescription: 'Cortes y cuidado personal masculino', cPathImage: '/imagenes/barberia.jpg' },
  { cName: 'Carnicería', csDescription: 'Cortes de carne fresca y de calidad', cPathImage: '/imagenes/carniceria.jpg' },
  { cName: 'Centro de estética', csDescription: 'Tratamientos de belleza y cuidado personal', cPathImage: '/imagenes/estetica.jpg' },
  { cName: 'Centro de tecnología', csDescription: 'Electrónica, gadgets y accesorios', cPathImage: '/imagenes/tecnologia.jpg' },
  { cName: 'Cine', csDescription: 'Disfruta de los últimos estrenos en la pantalla grande', cPathImage: '/imagenes/cine.jpg' },
  { cName: 'Café Internet', csDescription: 'Acceso a internet y servicios digitales', cPathImage: '/imagenes/internet_cafe.jpg' },
  { cName: 'Consultorio veterinario', csDescription: 'Salud y bienestar para tus mascotas', cPathImage: '/imagenes/veterinaria.jpg' },
  { cName: 'Droguería / Farmacia', csDescription: 'Medicamentos y productos de salud', cPathImage: '/imagenes/farmacia.jpg' },
  { cName: 'Entrega / Domicilios', csDescription: 'Servicios de entrega rápida y eficiente', cPathImage: '/imagenes/domicilios.jpg' },
  { cName: 'Estación de lavado', csDescription: 'Lava y embellece tu vehículo', cPathImage: '/imagenes/lavadero.jpg' },
  { cName: 'Ferretería', csDescription: 'Todo en herramientas y materiales de construcción', cPathImage: '/imagenes/ferreteria.jpg' },
  { cName: 'Floristería', csDescription: 'Flores frescas para cada ocasión', cPathImage: '/imagenes/floristeria.jpg' },
  { cName: 'Frutería / Tienda saludable', csDescription: 'Productos frescos y saludables', cPathImage: '/imagenes/fruteria.jpg' },
  { cName: 'Gimnasio', csDescription: 'Entrena y mejora tu condición física', cPathImage: '/imagenes/gimnasio.jpg' },
  { cName: 'Heladería', csDescription: 'Deliciosos helados y postres fríos', cPathImage: '/imagenes/heladeria.jpg' },
  { cName: 'Joyería', csDescription: 'Accesorios de lujo y regalos especiales', cPathImage: '/imagenes/joyeria.jpg' },
  { cName: 'Librería / Papelería', csDescription: 'Libros, cuadernos y material escolar', cPathImage: '/imagenes/libreria.jpg' },
  { cName: 'Licorera / Minimarket', csDescription: 'Bebidas y productos de conveniencia', cPathImage: '/imagenes/licorera.jpg' },
  { cName: 'Mercado / Supermercado', csDescription: 'Compra productos de tu canasta básica', cPathImage: '/imagenes/supermercado.jpg' },
  { cName: 'Mueblería', csDescription: 'Muebles y decoración para el hogar', cPathImage: '/imagenes/muebleria.jpg' },
  { cName: 'Nightclub / Discoteca', csDescription: 'Diversión nocturna, música y baile', cPathImage: '/imagenes/nightclub.jpg' },
  { cName: 'Panadería', csDescription: 'Pan fresco todos los días', cPathImage: '/imagenes/panaderia.jpg' },
  { cName: 'Peluquería', csDescription: 'Cortes y tratamientos capilares', cPathImage: '/imagenes/peluqueria.jpg' },
  { cName: 'Ropa de segunda / Reventa', csDescription: 'Moda sustentable y económica', cPathImage: '/imagenes/ropa_segunda.jpg' },
  { cName: 'Salón de tatuajes', csDescription: 'Arte corporal y diseño personalizado', cPathImage: '/imagenes/tatuajes.jpg' },
  { cName: 'Servicio técnico / Soporte', csDescription: 'Reparación de dispositivos y asistencia', cPathImage: '/imagenes/soporte_tecnico.jpg' },
  { cName: 'Spa', csDescription: 'Relajación y bienestar en un solo lugar', cPathImage: '/imagenes/spa.jpg' },
  { cName: 'Tienda de electrónica', csDescription: 'Dispositivos y tecnología actualizada', cPathImage: '/imagenes/electronica.jpg' },
  { cName: 'Tienda de mascotas', csDescription: 'Todo para el cuidado de tus animales', cPathImage: '/imagenes/mascotas.jpg' },
  { cName: 'Tienda de zapatos', csDescription: 'Calzado para todas las ocasiones', cPathImage: '/imagenes/zapateria.jpg' },
  { cName: 'Tienda general / Abarrotes', csDescription: 'Productos de uso diario y básicos', cPathImage: '/imagenes/abarrotes.jpg' },
  { cName: 'Tienda por departamentos', csDescription: 'Moda, hogar y más en un solo lugar', cPathImage: '/imagenes/por_departamentos.jpg' },
  { cName: 'Tienda tecnológica', csDescription: 'Últimos gadgets y dispositivos', cPathImage: '/imagenes/tienda_tecnologica.jpg' },
  { cName: 'Tienda vintage / Empeños', csDescription: 'Artículos usados y objetos únicos', cPathImage: '/imagenes/vintage.jpg' },
  { cName: 'Tienda de juguetes', csDescription: 'Diversión para los más pequeños', cPathImage: '/imagenes/jugueteria.jpg' },
  { cName: 'Zapatería', csDescription: 'Zapatos para todas las edades y estilos', cPathImage: '/imagenes/zapateria.jpg' },
  { cName: 'Lavandería', csDescription: 'Limpieza profesional de prendas', cPathImage: '/imagenes/lavanderia.jpg' }
]
