"""
Domain Entity: PaymentMethod
"""
type PaymentMethod {
  payId: ID!
  name: String!
  icon: String!
  state: String!
  paymentPriority: Int!
  createdAt: String
  updatedAt: String
}

input CreatePaymentMethodInput {
  payId: ID!
  name: String!
  icon: String!
  state: String!
  paymentPriority: Int!
  mIcon: Int
  mState: Int
}


input UpdatePaymentMethodInput {
  name: String
  icon: String
  state: String
  paymentPriority: Int
  mIcon: Int
  mState: Int
}

type Query {
  getPaymentMethod(payId: ID!): PaymentMethod
  getAllPaymentMethods: [PaymentMethod]
}