import Joi from 'joi'

/**
 * Joi schema for Product validation
 */
export const productSchema = Joi.object({
  pId: Joi.string().allow(null),
  idStore: Joi.string().allow(null),
  id: Joi.string().allow(null),
  carProId: Joi.string().allow(null),
  sizeId: Joi.string().allow(null),
  colorId: Joi.string().allow(null),
  cId: Joi.string().allow(null),
  dId: Joi.string().allow(null),
  ctId: Joi.string().allow(null),
  fId: Joi.string().allow(null),
  caId: Joi.string().allow(null),
  poPriority: Joi.number().integer().min(0).default(1),
  stock: Joi.number().integer().min(0).default(0),
  manageStock: Joi.boolean().default(true),
  previousStock: Joi.number().integer().min(0).default(0),
  valueDelivery: Joi.number().precision(2).min(0).default(0).allow(null),
  ValueDelivery: Joi.number().precision(2).min(0).default(0).allow(null),
  pName: Joi.string().required(),
  tgId: Joi.string().allow(null),
  pCode: Joi.string().max(100).required(),
  ProPrice: Joi.number().precision(2).max(999999999999.99).default(0.00),
  vat: Joi.number().precision(2).min(0).max(100).default(0.00),
  ProDescuento: Joi.number().precision(2).allow(null),
  ProUniDisponibles: Joi.number().integer().allow(null),
  ProDescription: Joi.string().allow(null),
  pState: Joi.number().valid(1, 0, -1).required(), // StateProduct enum
  sTateLogistic: Joi.number().required(),
  ProProtegido: Joi.number().integer().allow(null),
  ProAssurance: Joi.string().allow(null),
  ProStar: Joi.number().integer().allow(null),
  ProImage: Joi.string().allow(null),
  ProWidth: Joi.number().integer().allow(null),
  ProHeight: Joi.number().integer().default(1),
  free: Joi.number().integer().default(0),
  ProLength: Joi.string().default('1'),
  ProWeight: Joi.string().default('1'),
  ProQuantity: Joi.number().integer().allow(null),
  ProOutstanding: Joi.number().integer().allow(null),
  ProDelivery: Joi.number().integer().allow(null),
  ProVoltaje: Joi.string().allow(null),
  ProBarCode: Joi.string().min(1).max(50).allow(null),
  createdAt: Joi.date().default(Date.now),
  updatedAt: Joi.date().default(Date.now)
})
