type OrderTotals {
  key: String
  name: String
  value: String
}

# Stores
type StoreOrders {
  pdpId: ID
  id: ID
  idStore: ID
  ppState: Int
  channel: Int
  change: Int
  pCodeRef: String
  status: String
  pSState: ID
  payId: ID
  totalProductsPrice: Float
  unidProducts: Int
  createdAt: DateTime
  updatedAt: DateTime
  getUser: User
  shoppingCartRefCode: String
  locationUser: String
  date: DateTime
  store: Store
  shoppingCarts: [ShoppingCart]
  client: Clients
  getOneStore: Store
  totals: [OrderTotals]
  statusOrder: OrderStatusType
  paymentMethod: PaymentMethod
}
type OrderPapu {
  id: String
  idStore: String
  pdpId: String
  totalProductsPrice: Int
  unidProducts: Int
}

type ResponseSalesStore {
  success: Boolean
  message: String
  errors: [errors]
  data: StoreOrders
}

type Query {
  getOneSalesStore(pCodeRef: String): ResponseSalesStore
  getAllSalesStore: [StoreOrders]
}
