input InputManageStock {
  pId: ID
  manageStock: Boolean
}

type Query {
  getProductsInStock(limit: Int, offset: Int): [ProductFood]
}

type Mutation {
  updateManageStock(input: InputManageStock): ResponseProduct
}