# Types
type Message {
    uuid: String
    content: String
    from: String
    to: String
    aDatCre: String
}
# Queries
type Query {
    "Consulta todos los mensajes"
    getMessages(from: String): [Message]
    currentNumber: Int

}

# Mutations
type Mutation {
    "Registra un mensaje"
    sendMessage(to: String!, content: String!): Message
}
type Subscription {
    newMessage: Message!
    numberIncremented: Int
}