type Report {
    id: ID
    name: String
    description: String
    url: String
    createdAt: DateTime
}

type IResponseReport {
    success: Boolean
    message: String
    errors: [errors]
    data: Report
}

type Query {
    getReports: [IResponseReport]
    getReportById(id: ID!): IResponseReport
    getReportBydateRange(startDate: DateTime!, endDate: DateTime!): IResponseReport
    getReportDay(date: DateTime!): IResponseReport
    getReportDayNumber(day: Int!): IResponseReport
}