type Roles {
  idRole: ID
  name: String!
  priority: Int
  description: String
  permissions: JSON!
  createdAt: DateTime
  updatedAt: DateTime
}

input IRole {
  idRole: ID
  name: String! 
  priority: Int
  description: String
  createdAt: DateTime
  updatedAt: DateTime
}

type ResponseRoles {
    success: Boolean
    message: String
    errors: [errors]
    data: [Roles]
    pagination: Pagination 
}

type Query {
"""Response for Role"""
  getRole(idRole: ID, name: String): Roles!
  getRoles: ResponseRoles
}

type Mutation {
"""Response for user login"""
  createRoleMutation(input: IRole) : Roles
}