type StockMovement {
  idstockMoment: ID!
  productId: ID!
  movementType: MovementType!
  quantity: Int!
  previousStock: Int!
  newStock: Int!
  reference: String
  createdAt: String
  updatedAt: String
}
input StockMovementInput {
  productId: ID!
  movementType: MovementType!
  quantity: Int!
  previousStock: Int!
  newStock: Int!
  reference: String
}

enum MovementType {
  IN
  OUT
  ADJUSTMENT
}

type StockMovementSummary {
  date: String
  total_in: Int
  total_out: Int
}

type ProductMovement {
  productName: String!
  totalMovements: Int!
  idProduct: ID
}

type MonthlySales {
  month: String!
  totalSold: Int!
}


type Query {
  getStockMovements: [StockMovement!]!
  getStockMovementById(id: ID!): StockMovement
  getStockMovementsByDay: [StockMovementSummary!]!
  getTopProductsMovements: [ProductMovement]
  getMonthlySales: [MonthlySales!]!
  getTotalProductsInStock: Int!
  getTotalSalesSold: Int!

}

type responseStockMovement {
    data: StockMovement
    success: Boolean
    message: String
    errors: [errors]
}

type Mutation {
  createStockMovement(input: StockMovementInput!): responseStockMovement
}
